# TIDYR & DPLYR Practice

#For avoiding random generation of values
set.seed(1)

# Autogenerated Dataframe
stocks <- data.frame(time = as.Date('2009-01-01') + 0:9, Walmart = rnorm(10,20,1), Target = rnorm(10,20,2), Walgreens = rnorm(10,20,4))

# Create Key/Value Dataframe from stocks
stocks1 <- stocks %>% gather(key="stock", value="precio", Walmart, Walgreens)

# Revert stocks1 to stocks status
stocks2 <- stocks1 %>% spread(stock, precio)

# Run gather, group_by and summarise in the same order
stocks3 <- stocks %>% gather(key=stock, value=precio, "Walmart","Walgreens") %>% group_by(key=stock) %>% summarise(min = min(precio), max = max(precio))

# Flights
head(flights)
summary(flights)
flights_simple <- flights %>% head(100)
planes_simple <- planes %>% head(100)
airlines_simple <- airlines %>% head(100)
# Get Carriers from airlines dataset
airlines_carriers <- airlines_simple %>% select(carrier) %>% unique()
# Mean and max seats number of planes
planes_seats <-planes_simple %>% summarise(mean = mean(seats), max = max(seats))
# Sort by engines and seats
planes_sorted <- planes_simple %>% arrange(engines, seats)
# Carriers that used tailnum in fligths in dataset
carriers1 <- inner_join(planes_simple, flights_simple, by="tailnum")$carrier
# Get joined planes and fligths with two or more engines and same tailnum
anti_planes <- anti_join(planes, flights, by="tailnum")
anti_planes %>% filter(engines >= 2) %>% unique()
# Get modified dataframe with the sum of dep_delay and arr_delay as total_delay
flights_total <- mutate(flights, total_delay = flights$dep_delay + flights$arr_delay)
# Get the flights which total_delay is less than 0
before_arrive_fligths <- flights_total %>% filter(total_delay < 0)
